# Generated by Django 5.0.7 on 2024-08-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.URLField(default='https://www.youtube.com/embed/dC44dqf-6Cg?si=JlsdXurZXaLQeJkl', max_length=500),
        ),
    ]
