
services:
  db:
    image: postgres:16
    container_name: al_asal_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PORT=${DB_PORT}
    restart: always

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: al_asal_web
    command: gunicorn main.wsgi:application --bind 0.0.0.0:${DJANGO_PORT} --workers=4
    volumes:
      - ./:/app
      - ./static:/home/app/web/static
      - ./locales:/home/app/web/locales
      - ./media:/home/app/web/media
    security_opt:
      - seccomp:unconfined
    env_file:
      - .env
    environment:
      - TZ=Asia/Tashkent
    ports:
      - ${DJANGO_PORT}:${DJANGO_PORT}
    depends_on:
      - db
    restart: always

  # bot:
  #   build:
  #     context: ./
  #     dockerfile: compose/bot/Dockerfile
  #   container_name: al_asal_bot
  #   ports:
  #     - 8007:8007
  #   restart: always

volumes:
  postgres_data: