# Generated by Django 5.0.7 on 2024-09-02 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="order",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="product",
        ),
        migrations.RemoveField(
            model_name="saved",
            name="user",
        ),
        migrations.RemoveField(
            model_name="saveditem",
            name="saved",
        ),
        migrations.RemoveField(
            model_name="saveditem",
            name="product",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
        migrations.DeleteModel(
            name="Saved",
        ),
        migrations.DeleteModel(
            name="SavedItem",
        ),
    ]
