# Generated by Django 5.0.7 on 2024-09-05 17:33

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True, validators=[core.validators.PhoneNumberValidator()]),
        ),
    ]
