# Generated by Django 5.0.7 on 2024-10-05 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('warehouse', 'Warehouse'), ('delivery', 'Delivery')], default='admin', max_length=20),
        ),
    ]
