# Generated by Django 5.0.7 on 2024-08-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramuser",
            name="token",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
